spring:
  application:
    name: DaoHibernate
  datasource:
    url: jdbc:postgresql://localhost:5432/my_new_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

sql:
  init:
    mode: always
    schema-locations: classpath:schema.sql

server:
  port: 8080
